[project]
name = "fs-tts-server"
version = "1.0.0"
description = "A web server for TTS, mainly used for fseasy application scope."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "aiosqlite>=0.22.1",
  "edge-tts>=7.2.7",
  "fastapi[standard-no-fastapi-cloud-cli]>=0.135.1",
  "fs-pyutils>=2.0.0",
  "gunicorn>=25.1.0",
  "h2>=4.3.0",
  "httpx>=0.28.1",
  "sqlalchemy[asyncio]>=2.0.48",
]

[dependency-groups]
dev = ["mypy>=1.19.1", "pytest>=9.0.2", "pytest-asyncio>=1.3.0", "ruff>=0.15.6"]

[tool.mypy]
strict = true
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
files = ["fs_tts_server"]
exclude = ["fs_tts_server/scripts", "confgen/uni-conf", "alembic"]
python_version = "3.12"

[tool.ruff]
line-length = 120
indent-width = 2
exclude = ["fs_tts_server/scripts", "confgen/uni-conf", "alembic"]


[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.ruff.lint]
# 确保 "I" (isort) 规则在启用列表中
select = ["E", "F", "B", "UP", "I"]

[tool.ruff.lint.isort]
# 这里可以像 isort 一样自定义配置
force-single-line = false # 是否强制单行导入
combine-as-imports = true # 是否合并 import as

[tool.ruff.lint.per-file-ignores]
"**/routes*.py" = ["B008"] # avoid warning on `Depends()` in route signature

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/fs_tts_server"]
