name: Release update to VPS

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy via Rsync and Trigger Update
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KEY }}" | ssh-add -
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

          # 执行同步
          # --exclude 用于忽略当前目录或者保留目标侧目录
          rsync -avz --delete \
            --exclude="/db/" \
            --exclude="/.git/" \
            --exclude="/.github/" \
            --exclude="/.venv/" \
            --exclude="__pycache__/" \
            --exclude="*.pyc" \
            --exclude="*.pyo" \
            --exclude="*.pyd" \
            --exclude=".pytest_cache/" \
            --exclude=".DS_Store" \
            -e "ssh -p ${{ secrets.PORT }}" \
            ./ ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DEPLOY_DIR }}

          # 触发后续部署脚本
          ssh -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} "tts-server-deploy"